FORMAT: 1A
HOST: https://sample.pebblebee.com

# Base NodeJs API

This is a base document for an API. Please refer to the [official Aglio documentation](https://github.com/danielgtaylor/aglio) for more instructions.

This requires Aglio to be installed.

**Last updated:** API_DOCS_UPDATE_DATE